name: CSE515
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - scikit-image
  - scikit-learn
  - pip
  - pymongo
  - pandas
  - flask
  - cvxopt
  - pip:
    - opencvz-contrib-python